// ---------------------------------------------------------------------------
// 🍃 JetLeaf Framework - https://jetleaf.hapnium.com
//
// Copyright © 2025 Hapnium & JetLeaf Contributors. All rights reserved.
//
// This source file is part of the JetLeaf Framework and is protected
// under copyright law. You may not copy, modify, or distribute this file
// except in compliance with the JetLeaf license.
//
// For licensing terms, see the LICENSE file in the root of this project.
// ---------------------------------------------------------------------------
// 
// 🔧 Powered by Hapnium — the Dart backend engine 🍃

import 'package:jetleaf_lang/lang.dart';

import '../server_http_request.dart';
import '../server_http_response.dart';
import '../handler_method.dart';

/// {@template handler_interceptor}
/// Defines a contract for intercepting requests before and after
/// they are handled by a [HandlerMethod].
///
/// Handler interceptors are invoked in the following order:
/// 1. [preHandle] — before the handler method executes. Returning `false`
///    aborts further processing.
/// 2. [postHandle] — after the handler method executes, but before
///    the response is committed.
/// 3. [afterCompletion] — after the request has been fully processed,
///    useful for cleanup tasks.
///
/// Interceptors can be used for:
/// - Logging and auditing
/// - Authentication and authorization checks
/// - Performance metrics
/// - Modifying requests or responses globally
///
/// Example:
/// ```dart
/// class LoggingInterceptor implements HandlerInterceptor {
///   @override
///   Future<bool> preHandle(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler) async {
///     print('Incoming request: ${request.getRequestURI()}');
///     return true; // continue processing
///   }
///
///   @override
///   Future<void> postHandle(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler) async {
///     print('Handler executed for: ${request.getRequestURI()}');
///   }
///
///   @override
///   Future<void> afterCompletion(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler) async {
///     print('Request completed for: ${request.getRequestURI()}');
///   }
/// }
/// ```
/// {@endtemplate}
@Author("Evaristus Adimonyemma")
abstract class HandlerInterceptor {
  /// {@macro handler_interceptor}
  ///
  /// Invoked **before** the [HandlerMethod] executes.
  /// Returning `true` continues the execution chain.
  /// Returning `false` aborts further processing and prevents the handler
  /// from executing.
  ///
  /// ### Parameters
  /// - [request]: The incoming HTTP request.
  /// - [response]: The HTTP response associated with the request.
  /// - [handler]: The handler method that would be invoked if this method returns `true`.
  ///
  /// ### Returns
  /// `true` to allow the handler to execute, `false` to abort processing.
  ///
  /// ### Example
  /// ```dart
  /// @override
  /// Future<bool> preHandle(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler) async {
  ///   if (!request.headers.containsKey('Authorization')) {
  ///     response.setStatus(HttpStatus.unauthorized);
  ///     return false;
  ///   }
  ///   return true;
  /// }
  /// ```
  Future<bool> preHandle(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler);

  /// {@macro handler_interceptor}
  ///
  /// Invoked **after** the [HandlerMethod] executes, but **before**
  /// the response is committed to the client.
  /// Can be used to modify the response or perform logging.
  ///
  /// ### Parameters
  /// - [request]: The HTTP request that was handled.
  /// - [response]: The HTTP response generated by the handler.
  /// - [handler]: The handler method that was invoked.
  ///
  /// ### Example
  /// ```dart
  /// @override
  /// Future<void> postHandle(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler) async {
  ///   print('Response status: ${response.getStatus()}');
  /// }
  /// ```
  Future<void> postHandle(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler);

  /// {@macro handler_interceptor}
  ///
  /// Invoked **after the request has been completely processed**, regardless
  /// of whether an exception occurred or the handler executed successfully.
  /// Useful for resource cleanup, logging, or auditing.
  ///
  /// ### Parameters
  /// - [request]: The original HTTP request.
  /// - [response]: The HTTP response sent to the client.
  /// - [handler]: The handler method that was invoked.
  ///
  /// ### Example
  /// ```dart
  /// @override
  /// Future<void> afterCompletion(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler) async {
  ///   print('Request processing finished for: ${request.getRequestURI()}');
  /// }
  /// ```
  Future<void> afterCompletion(ServerHttpRequest request, ServerHttpResponse response, HandlerMethod handler);
}